import { ProjectData } from "@/components/ProjectCard/ProjectCard";

export const allProjects: ProjectData[] = [
  { id: 0, title: "posfyi", subtitle: "SaaS fintech · payments on any Android", description: "Full-stack SaaS payments platform letting retail merchants accept UPI, NFC, and card payments through their Android phone — no POS hardware needed. PCI-DSS L1, RBI PA-PG compliant. 4,200+ active merchants, ₹62 Cr processed monthly across 14 states.", tech: ["Next.js", "React Native", "TypeScript", "Razorpay", "Node.js"], href: "https://posfyi.com", color: "#38bdf8", media: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80" },
  { id: 1, title: "AI Repo Analyzer", subtitle: "Reverse-engineer any GitHub repo instantly", description: "High-performance AI system that reverse-engineers GitHub repositories into structured engineering insights — architecture inference, scalability analysis, and code quality evaluation using Groq LLM.", tech: ["Next.js", "TypeScript", "Groq", "GitHub API"], href: "/repoAnalyzer", color: "#64ffda", media: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80" },
  { id: 2, title: "Product Spider", subtitle: "AI-powered e-commerce aggregator", description: "AI-powered product search engine aggregating results from Amazon, Flipkart, Myntra and more — Groq LLM for natural language query understanding, relevance ranking, and affiliate-tagged direct links.", tech: ["Next.js", "TypeScript", "Groq", "Serper API", "RapidAPI"], href: "/productSpider", color: "#f7c948", media: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80" },
  { id: 3, title: "Arb⚡SCAN", subtitle: "Real-time arbitrage scanner with AuthGate", description: "Live arbitrage scanner that monitors price discrepancies across exchanges and surfaces opportunities in real time — WebSocket feeds, custom scoring logic, and ultra-low latency frontend and authentication.", tech: ["Next.js", "TypeScript", "WebSockets", "REST APIs"], href: "/arbScanner", color: "#ff6b6b", media: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80" },
  { id: 4, title: "TCS × Kenvue", subtitle: "Enterprise mobile · TCS × Kenvue", description: "Worked on 3+ mobile enterprise apps, in multiple frontend technologies for Kenvue's consumer engagement platform, with multiple features and REST APIs integrated.", tech: ["React Native", "Next.js", "Zustand", "TypeScript"], href: "#", color: "#a78bfa", media: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80" },
  { id: 6, title: "Learnerula", subtitle: "Adaptive e-learning platform", description: "Adaptive e-learning platform with a Word Spin vocabulary game featuring user-segmentation logic that dynamically adjusts content difficulty based on learner proficiency scores.", tech: ["React Native", "JavaScript", "REST APIs"], href: "#", color: "#34d399", media: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80" },
];